# Generated by Django 4.2.11 on 2026-04-14 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databaseconnection',
            name='password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
